/**:
  ros__parameters:
    joints_map:
      left_front:
        - FL_hip_yaw
        - FL_thigh_pitch
        - FL_knee_pitch
        - FL_foot_fixed
      right_front:
        - FR_hip_yaw
        - FR_thigh_pitch
        - FR_knee_pitch
        - FR_foot_fixed
      left_hind:
        - BL_hip_yaw
        - BL_thigh_pitch
        - BL_knee_pitch
        - BL_foot_fixed
      right_hind:
        - BR_hip_yaw
        - BR_thigh_pitch
        - BR_knee_pitch
        - BR_foot_fixed
