stand_controller:
  ros__parameters:
    dh:
      L_hh: 0.02553
      L_th: 0.11725
      L_sh: 0.07043
    stand:
      default_height: 0.18
      ramp_time: 2.0
      publish_rate: 50.0
      knee_direction: 1
    joint_order:
      - FL_hip_yaw
      - FL_thigh_pitch
      - FL_knee_pitch
      - FR_hip_yaw
      - FR_thigh_pitch
      - FR_knee_pitch
      - BL_hip_yaw
      - BL_thigh_pitch
      - BL_knee_pitch
      - BR_hip_yaw
      - BR_thigh_pitch
      - BR_knee_pitch
